### ISSUE TITLE
Errors building - missing files

### ISSUE THREAD

**Issue by rickysahu** [lancetw/react-isomorphic-bundle#1]
I'm getting a few errors during the build process. Specifically, one around the use of leveldb, and another with the missing react-isomorphic-bundle/storage/webpack-stats.json file. The demo looks great and I hope to get off the ground with this. Thanks for making this.

**leveldb**
events.js:85
      throw er; // Unhandled 'error' event
            ^
OpenError: IO error: ./storage/leveldb/LOCK: No such file or directory
    at /Users/machine/Desktop/git/react-isomorphic-bundle/node_modules/levelup/lib/levelup.js:119:34
    at /Users/machine/Desktop/git/react-isomorphic-bundle/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
9 Jul 04:28:25 - [nodemon] app crashed - waiting for file changes before starting...

**Missing webpack-stats**
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/Users/machine/Desktop/git/react-isomorphic-bundle/storage/webpack-stats.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Tapable.exports.default (/Users/machine/Desktop/git/react-isomorphic-bundle/webpack/utils/write-stats.js:46:6)

**Comment by lancetw** [comment]
@rickysahu Now should works, just missing storage folder.
