### ISSUE TITLE
Post component fails on server rendering

### ISSUE THREAD

**Issue by kikoanis** [lancetw/react-isomorphic-bundle#4]
Currently if you go /post and try to hard refresh the page, you get 500 error message.
```
TypeError: [tcomb] [tcomb-form] missing required prop type
```

tried to figure out what is it with no success.

![screenshot from 2015-09-20 17 00 43](https://cloud.githubusercontent.com/assets/615849/9983442/4398ec78-5fb9-11e5-8f73-f886181b3628.png)

**Comment by lancetw** [comment]
@kikoanis you could try to delete node_modules and run `npm install`.

**Comment by kikoanis** [comment]
Tried that still no success. I can see the same issue on your demo website.

**Comment by lancetw** [comment]
@kikoanis Thanks for your report, I think this bug is about the locale (counterpart), I will try to figure out.

For now you could try to replace all `counterpart.getLocale()` to 'en'.

**Comment by kikoanis** [comment]
@lancetw The thing is that it does not happen on other components like change password or manage. Only on Post component. I know it is related to comb-form. Seems to me that the Router.run does not get all required props when it tries to set the initial state. Still not sure why only on Post. Maybe because of composability of the component. I really can't tell. This is one of the frustrating parts of using React where when things go south, you may spend hours to debug an issue that could be solved with a tiny switch.

**Comment by kikoanis** [comment]
@lancetw that makes sense.

I did more investigation and it seems that this line 
https://github.com/lancetw/react-isomorphic-bundle/blob/master/src/server/appView.js#L75 
in appView.js is causing the issue. On my machine it returns 'en-GB' which does not map to any of your translation settings.

**Comment by kikoanis** [comment]
As a quick fix and since we have only one "English" translation settings (Locale)
You could fix this line
https://github.com/lancetw/react-isomorphic-bundle/blob/master/src/shared/utils/locale-utils.js#L23
with this
```
  if (locale && locale.startsWith('en')) {
    return 'en'
  }
```

**Comment by lancetw** [comment]
Thanks!

**Comment by kikoanis** [comment]
Thank YOU for putting this sample together. I personally have learned a lot from it.

One question though,

Are you considering upgrading react-route to 1.0.0-rc1. it seems to me that it is a different implementation?

**Comment by kikoanis** [comment]
I see you already did that. Great thanks
