### ISSUE TITLE
Issues with LocaleChange

### ISSUE THREAD

**Issue by kikoanis** [lancetw/react-isomorphic-bundle#6]
I see nearly in every component to fire an even change for counterpart in the constructor 

``` counterpart.onLocaleChange(::this.handleLocaleChange) ```
 but you never release that event.

This will cause issues as it will fire the event change even if the component is not mounted.

I think you need to handle locale change only in ``` componentDidMount() ```
and you need to clear the event change in ``` componentWillUnmount () ```

Otherwise you will see this warning always nearly in every component.

``` setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for (component) ```

I see you have a base component and I think this would be the place to handle locale change if a component inherits from it. If you are against the idea of inheritance in JS (I am), you might consider using higher order components instead.

**Comment by lancetw** [comment]
Thanks so much for your tips, I'll figure it out later.

**Comment by kikoanis** [comment]
Thanks for fixing. Though, it seems to me that there is a lot of redundant code related to locale change. I managed to put some code to manage locale change in a higher order component.

Have a look here https://github.com/kikoanis/react-isomorphic-bundle/commit/ef11adf88e4ad690444f5175da87cfa795712df9  and here https://github.com/kikoanis/react-isomorphic-bundle/commit/ca08ae9bee7079bf167993d12861b69cacc7ad54

and let me know if you can embed it in your code so I can do a PR

**Comment by lancetw** [comment]
@kikoanis Thanks so much for sharing HoC tips.

But this repo is just a personal work (and practices) and prefer to use some libraries more than pr. :smile:

**Comment by kikoanis** [comment]
Fair enough... Thank you for sharing the repo anyway

**Comment by lancetw** [comment]
@kikoanis I borrowed your code (see 448dcdd) and BaseComponent is gone, thank you a lot.

**Comment by kikoanis** [comment]
Great! Looks even better. Glad if I was of some help.
