### ISSUE TITLE
App is not running (though everything seemed fine)

### ISSUE THREAD

**Issue by philohelp** [lancetw/react-isomorphic-bundle#8]
I try to go and see http://127.0.0.1:3000 but all I get is Failed to load resource: net::ERR_CONNECTION_REFUSED. Its curious because all the bundling was made without error. The app looks great, It's disappointing.... what did I do wrong ? Thank you.

**Comment by lancetw** [comment]
Make sure you have change the database dialect to `sqlite` before you run the app (default is `postgres`).
